export default {
    bgImage: require('../assets/images/bgImage.jpeg'),
    icBack: require('../assets/images/ic_back.png'),
    icShow: require('../assets/images/ic_visible.png'),
    icHide: require('../assets/images/ic_hide.png'),
    icLoc: require('../assets/images/ic_loc.png'),
    icChat: require('../assets/images/ic_chat.png'),
    icCamera: require('../assets/images/ic_camera.png'),
    icPeople: require('../assets/images/ic_people.png'),
    icSearch: require('../assets/images/ic_search.png'),
    icAdd: require('../assets/images/ic_add.png'),
    icMore: require('../assets/images/ic_more.png'),
    icClose: require("../assets/images/close.png"),
    icNavigation: require("../assets/images/navigation.png"),
    icSetting : require("../assets/images/ic_setting.png"),
    //bitemoji
    emoji1: require('../assets/images/bitemoji/emoji1.png'),
    emoji2: require('../assets/images/bitemoji/emoji2.png'),
    emoji3: require('../assets/images/bitemoji/emoji3.png'),
    emoji4: require('../assets/images/bitemoji/emoji4.png'),
    emoji5: require('../assets/images/bitemoji/emoji5.png'),
}
